server:
  port: 9002

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
       # 单机版
       # server-addr: localhost:8848 #配置Nacos地址
        #nocas集群的话,需要填集群中nginx的地址
        server-addr: nacos.cluster.com:80 #配置Nacos地址

management:
  endpoints:
    web:
      exposure:
        include: '*'