server:
  port: 800

spring:
  application:
    name: consul-consumer-order
  cloud:
    consul:
      host: 192.168.29.102
      port: 8500
      discovery:
        hostname: 192.168.29.1
        service-name: ${spring.application.name}